version: '3.8'

services:
  react-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      NODE_ENV: production
